/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package InterfazVisual;
import Backend_Logica_Eventos.Evento;
import Backend_Logica.Direccion;
import java.time.LocalDateTime;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import InterfazVisual.CrearEventoFrame;
import Backend_Logica_Eventos.GestorArchivosEventos;
import javax.swing.JOptionPane;


/**
 *
 * @author harou
 */
public class AdminEventosFrame extends javax.swing.JFrame {
    /**
     * Creates new form NewJFrame
     */
    private ArrayList<Evento> eventos;
    private DefaultTableModel modelo; // Atributo de clase
    
    public AdminEventosFrame() {
        initComponents();

        modelo = new DefaultTableModel();
        modelo.addColumn("Título");
        modelo.addColumn("Tipo");
        modelo.addColumn("Ciudad");
        modelo.addColumn("Fecha");
        modelo.addColumn("Precio");
        modelo.addColumn("Máx. entradas");

        eventos = GestorArchivosEventos.cargarEventos(); // Primero carga los eventos

        actualizarComboTipos(); // Ahora sí puedes usar la lista


        for (Evento e : eventos) {
            modelo.addRow(new Object[]{
                e.getTitulo(),
                e.getTipo(),
                e.getDireccion().getCiudad(),
                e.getFecha().toString(),
                e.getPrecio(),
                e.getMaxEntradas()
            });
        }

        tablaEventos.setModel(modelo);
    }

    
    private void actualizarComboTipos() {
    Tipo.removeAllItems();
    Tipo.addItem("Todos");

    java.util.Set<String> tiposUnicos = new java.util.HashSet<>();
    for (Evento e : eventos) {
        tiposUnicos.add(e.getTipo());
    }

    for (String tipo : tiposUnicos) {
        Tipo.addItem(tipo);
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        jToolBar1 = new javax.swing.JToolBar();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Ciudad = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        Tipo = new javax.swing.JComboBox<>();
        Buscar = new javax.swing.JButton();
        limpiarFiltros = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaEventos = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        jScrollPane3.setViewportView(jEditorPane1);

        jToolBar1.setRollover(true);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Filtrar por: ");
        jPanel2.add(jLabel1);

        Ciudad.setText("Ciudad");
        Ciudad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CiudadActionPerformed(evt);
            }
        });
        jPanel2.add(Ciudad);

        jLabel2.setText("Tipo: ");
        jPanel2.add(jLabel2);

        Tipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        Tipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TipoActionPerformed(evt);
            }
        });
        jPanel2.add(Tipo);

        Buscar.setText("Buscar");
        Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarActionPerformed(evt);
            }
        });
        jPanel2.add(Buscar);

        limpiarFiltros.setText("Limpiar Filtros");
        limpiarFiltros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpiarFiltrosActionPerformed(evt);
            }
        });
        jPanel2.add(limpiarFiltros);

        tablaEventos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaEventos);

        jButton2.setText("Añadir Evento");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton2);

        jButton3.setText("Editar Evento");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton3);

        jButton4.setText("Eliminar Evento");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton4);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 752, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jScrollPane1.getAccessibleContext().setAccessibleName("");
        jScrollPane1.getAccessibleContext().setAccessibleDescription("");

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // Averiguamos qué fila está seleccionada
        int filaSeleccionada = tablaEventos.getSelectedRow();

        if (filaSeleccionada >= 0) {                       // Hay algo seleccionado
            // Mensaje de confirmación
            int confirm = JOptionPane.showConfirmDialog(
                    this,
                    "¿Estás seguro de eliminar el evento seleccionado?",
                    "Confirmar eliminación",
                    JOptionPane.YES_NO_OPTION
            );

            if (confirm == JOptionPane.YES_OPTION) {
                // 1. Quitarlo de la lista en memoria
                eventos.remove(filaSeleccionada);

                // 2. Quitar la fila del modelo de la tabla
                modelo.removeRow(filaSeleccionada);

                // 3. Persistir el cambio en disco
                GestorArchivosEventos.guardarEventos(eventos);

                JOptionPane.showMessageDialog(this, "Evento eliminado correctamente.");
                actualizarComboTipos();
            }
        } else {                                           // Nada seleccionado
            JOptionPane.showMessageDialog(this, "Selecciona un evento para eliminar.");
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        int filaSeleccionada = tablaEventos.getSelectedRow();
        if (filaSeleccionada >= 0) {
            Evento eventoSeleccionado = eventos.get(filaSeleccionada);
            CrearEventoFrame editar = new CrearEventoFrame(modelo, eventos, eventoSeleccionado, filaSeleccionada);
            editar.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent e) {
                actualizarComboTipos();
            }
        });
        editar.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "Selecciona un evento para editar.");
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        CrearEventoFrame crear = new CrearEventoFrame(modelo, eventos);
        crear.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent e) {
                actualizarComboTipos();
            }
        });
        crear.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void CiudadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CiudadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CiudadActionPerformed

    private void TipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TipoActionPerformed

    private void BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarActionPerformed
        String ciudadFiltro = Ciudad.getText().trim().toLowerCase();
        String tipoFiltro = Tipo.getSelectedItem().toString();

        modelo.setRowCount(0); // limpiar tabla

        for (Evento e : eventos) {
            boolean coincideCiudad = ciudadFiltro.isEmpty() || e.getDireccion().getCiudad().toLowerCase().contains(ciudadFiltro);
            boolean coincideTipo = tipoFiltro.equals("Todos") || e.getTipo().equals(tipoFiltro);

            if (coincideCiudad && coincideTipo) {
                modelo.addRow(new Object[]{
                    e.getTitulo(),
                    e.getTipo(),
                    e.getDireccion().getCiudad(),
                    e.getFecha().toString(),
                    e.getPrecio()
                });
            }
        }

        if (modelo.getRowCount() == 0) {
            JOptionPane.showMessageDialog(this, "No se encontraron eventos con esos filtros.");
        }
    }//GEN-LAST:event_BuscarActionPerformed

    private void limpiarFiltrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpiarFiltrosActionPerformed
        Ciudad.setText("");                  // Borra el campo de texto de ciudad
        Tipo.setSelectedIndex(0);           // Selecciona "Todos" en el combo

        modelo.setRowCount(0);              // Borra todas las filas de la tabla

        for (Evento e : eventos) {          // Vuelve a añadir todos los eventos
            modelo.addRow(new Object[]{
                e.getTitulo(),
                e.getTipo(),
                e.getDireccion().getCiudad(),
                e.getFecha().toString(),
                e.getPrecio()
            });
        }
    }//GEN-LAST:event_limpiarFiltrosActionPerformed
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminEventosFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminEventosFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminEventosFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminEventosFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new AdminEventosFrame().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Buscar;
    private javax.swing.JTextField Ciudad;
    private javax.swing.JComboBox<String> Tipo;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JButton limpiarFiltros;
    private javax.swing.JTable tablaEventos;
    // End of variables declaration//GEN-END:variables
}
