    package InterfazVisual;

    import Backend_Logica.GestionDatos;
    import Backend_Logica_Clientes.Cliente;
    import Backend_Logica_Reservas.GestorArchivosReservas;
    import Backend_Logica_Reservas.Reserva;
    import javax.swing.*;
    import javax.swing.table.DefaultTableModel;
    import java.util.List;

    public class ReservasClientes extends javax.swing.JFrame {

        private String correoCliente;
        private GestionDatos gestion;
        private Cliente cliente;
        private javax.swing.JTable tablaReservas;


        public ReservasClientes(GestionDatos gestion, String correoCliente) {
            this.correoCliente = correoCliente;
            this.gestion = gestion;
            this.cliente = gestion.getClienteLogeado(); 
            initComponents();
            
            tablaReservas = new JTable(new DefaultTableModel(
                new Object[][] {},
                new String[] {"Título", "Fecha", "Total"}
            ));
            JScrollPane scrollPane = new JScrollPane(tablaReservas);
            getContentPane().setLayout(null); // para usar .setBounds directamente
            scrollPane.setBounds(20, 20, 360, 250);
            getContentPane().add(scrollPane);

            this.setLocationRelativeTo(null);
            cargarTabla();
        }


        
        private void cargarTabla() {
            DefaultTableModel modelo = (DefaultTableModel) tablaReservas.getModel();
            modelo.setRowCount(0);

            List<Reserva> reservas = GestorArchivosReservas.obtenerReservasCliente(correoCliente);
            for (Reserva r : reservas) {
                modelo.addRow(new Object[]{
                    r.getEvento().getTitulo(),
                    r.getFechaReserva(),
                    r.getTotal() + "€"
                });
            }
        }
        
        public ReservasClientes() {
            this(new GestionDatos(), "cliente@dummy.com");
}



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReservasClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReservasClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReservasClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReservasClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReservasClientes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
