/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package InterfazVisual;
import Backend_Logica.GestorDatosSerializador;
import Backend_Logica.GestionDatos;
/**
 *
 * @author anton
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    private GestionDatos gestor;
    
    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        gestor = GestorDatosSerializador.cargar();
        this.setLocationRelativeTo(null);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        titulo = new javax.swing.JLabel();
        boton_IniciarSesion = new javax.swing.JButton();
        boton_CrearCuenta = new javax.swing.JButton();
        texto_IniciarSesion = new javax.swing.JLabel();
        texto_CrearUsuario = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("JavaEvents");
        getContentPane().setLayout(new java.awt.GridBagLayout());

        titulo.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        titulo.setForeground(new java.awt.Color(30, 30, 30));
        titulo.setText("Bienvenido a JavaEvents");
        titulo.setToolTipText("");
        titulo.setAlignmentX(0.5F);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 36, 0, 54);
        getContentPane().add(titulo, gridBagConstraints);

        boton_IniciarSesion.setBackground(new java.awt.Color(0, 51, 204));
        boton_IniciarSesion.setAlignmentX(0.5F);
        boton_IniciarSesion.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        boton_IniciarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_IniciarSesionActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 57;
        gridBagConstraints.ipady = 26;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 112, 119, 0);
        getContentPane().add(boton_IniciarSesion, gridBagConstraints);

        boton_CrearCuenta.setBackground(new java.awt.Color(0, 51, 204));
        boton_CrearCuenta.setAlignmentX(0.5F);
        boton_CrearCuenta.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        boton_CrearCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_CrearCuentaActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 70;
        gridBagConstraints.ipady = 26;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 121, 119, 0);
        getContentPane().add(boton_CrearCuenta, gridBagConstraints);

        texto_IniciarSesion.setBackground(new java.awt.Color(51, 153, 255));
        texto_IniciarSesion.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        texto_IniciarSesion.setText("Iniciar Sesión");
        texto_IniciarSesion.setAlignmentX(0.5F);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(78, 93, 0, 0);
        getContentPane().add(texto_IniciarSesion, gridBagConstraints);

        texto_CrearUsuario.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        texto_CrearUsuario.setText("Crear Usuario");
        texto_CrearUsuario.setAlignmentX(0.5F);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(78, 98, 0, 0);
        getContentPane().add(texto_CrearUsuario, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void boton_CrearCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_CrearCuentaActionPerformed
        // TODO add your handling code here:
        CrearUsuario crearUsuario = new CrearUsuario(this, gestor);
        crearUsuario.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_boton_CrearCuentaActionPerformed

    private void boton_IniciarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_IniciarSesionActionPerformed
        // TODO add your handling code here:
        InicioSesion iniciar_sesion = new InicioSesion(this, gestor);
        iniciar_sesion.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_boton_IniciarSesionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boton_CrearCuenta;
    private javax.swing.JButton boton_IniciarSesion;
    private javax.swing.JLabel texto_CrearUsuario;
    private javax.swing.JLabel texto_IniciarSesion;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
